# Generated by Django 5.1.6 on 2025-05-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
